can i just run this code: /*
 * sd_card.c
 *
 *  Created on: Nov 30, 2025
 *      Author: Jonathan
 */

// One confusing thing about this code that I had to wrap my head around is how the SD card interacts with the SPI
// It's basically all handled through FatFs since it calls low level disk functions that handle the transfer of the image
// Through SPI and we then read the image as raw data.


// Also the files have to be in the root directory of the SD card to be able to read.
// Also have to handle JPEG to RGB565 conversion externally using Python
#include "xparameters.h" // Brings all hardware configurations constants generated by Vivado
#include "xil_printf.h" // printf over UART
#include "xil_types.h" //u8, u32
#include "xil_cache.h" // enable/disable and manage CPU cache
#include "ff.h" // FatFs file system
#include "xspi.h" // SPI driver for the AXI Quad SPI

// Image Specifications

#define IMG_WIDTH 640
#define IMG_HEIGHT 480
#define BYTES_PER_PIXEL 2
#define IMAGE_SIZE (IMG_WIDTH * IMG_HEIGHT * BYTES_PER_PIXEL)
u8 image_buffer[IMAGE_SIZE]; // 8-bit image buffer to hold one image frame in an array of size 614400

FATFS fatfs; // file system object that FatFs uses to keep track of the mounted SD card
// think of it like USB being connected to computer (mounted) and to remove USB you need to eject (unmounted)

int sd_mount(void){ // mounting the SD card
	FRESULT res; // storing the result of the file system operation

	xil_printf("Mounting the SD card..\r\n"); // waiting to mount the SD card
	res = f_mount(&fatfs, "0:/", 0); // Mounting the SD card using f_mount function that points to the global fatfs variable
	// you also save it as a 0:/ drive
	if (res != FR_OK){ // if the function did not succeed
		xil_printf("f_mount failed: %d\r\n", res);
		return XST_FAILURE; //
	}

	xil_printf("SD card mounted.\r\n");
	return XST_SUCCESS;
}

int sd_load_file (const char *name, u8 *dst, u32 max_bytes){
	FIL file; // file object structure
	FRESULT res;
	UINT br; // stores the number of bytes

	xil_printf ("Opening %s...\r\n", name); // opening file/printing a string
	res = f_open(&file, name, FA_READ); // open for reading only
	if (res != FR_OK){
		xil_printf("f_open failed: %d\r\n", res);
		return XST_FAILURE;
	}

	res = f_read(&file, dst, max_bytes, &br); // reading the data into the buffer and storing the number of bytes read
	f_close(&file);

	if (res != FR_OK){ // we input this again after reading the data from the file
		xil_printf("f_open failed: %d\r\n", res);
		return XST_FAILURE;
	}

	xil_printf("Read %u bytes from %s\r\n", br, name);
	return XST_SUCCESS;
}

int main(){
	int status;

	microblaze_enable_dcache(); // enabling data cache in microblaze

	xil_printf("SD card test starting...\r\n");

	status = sd_mount();

	if (status != XST_SUCCESS){
		xil_printf("SD mount failed\r\n");
		while (1);
	}

	status = sd_load_file("img0.raw", image_buffer, IMAGE_SIZE);
	if (status != XST_SUCCESS){
		xil_printf("File Read failed\r\n");
		while (1);
	}

	xil_printf("First 16 bytes of img0.raw:\r\n");
	for(u32 i = 0; i < 16; i++){
		xil_printf("%02X ", image_buffer[i]); // prints each line as a 2 digit hex number (16 bytes)
	}
	xil_printf("\r\nDone.\r\n");

	while(1);
	return 0;
}
